erDiagram
    T001W {
        string WERKS PK "Plant Code"
        string NAME1 "Plant Name"
    }
    T006A {
        string SPRAS PK "Language Key"
        string MSEHI PK "UOM Key"
        string MSEHL "UOM Text"
    }
    TJ30T {
        string STSMA PK "Status Profile"
        string ESTAT PK "User Status Code"
        string SPRAS PK "Language Key"
        string TXT30 "Status Description"
    }
    ADR6 {
        string ADDRNUMBER PK "Address Number"
        string PERSNUMBER PK "Person Number"
        string DATE_FROM PK "Valid From Date"
        string CONSNUMBER PK "Sequence Number"
        string SMTP_ADDR "E-Mail Address"
    }
    T052 {
        string ZTERM PK "Terms of Payment Key"
    }
